language: node_js
node_js:
  - lts/*
sudo: false
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.19.0-1
services:
  - postgresql
before_script:
  - psql -c 'create database technoapp;' -U postgres
cache:
  yarn: true
install:
  - yarn
